<?php if($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <?php if(isset($this->previous)): ?>
            <li>
                <a href="<?= $this->url($this->route); ?>?page=<?= $this->previous ?>"><<</a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a href="#" onclick="return false;"><<</a>
            </li>
        <?php endif; ?>

        <?php foreach($this->pagesInRange as $page): ?>
            <?php if($page != $this->current): ?>
                <li>
                    <a href="<?= $this->url($this->route); ?>?page=<?= $page; ?>"><?= $page; ?></a>
                </li>
            <?php else: ?>
                <li>
                    <a href="#"><?= $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach;?>

        <?php if(isset($this->next)): ?>
            <li><a href="<?= $this->url($this->route); ?>?page=<?= $this->next ?>">>></a></li>
        <?php else: ?>
            <li class="disabled">
                <a href="#" onclick="return false;">>></a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif;?>
